/*
 * Copyright (c) 2024, Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef NRFX_RESERVED_RESOURCES_H__
#define NRFX_RESERVED_RESOURCES_H__

/** @brief Bitmask that defines GPIOTE130 channels reserved for use outside
 *         of the nrfx library.
 */
#define NRFX_GPIOTE130_CHANNELS_USED                                                               \
	(~NRFX_CONFIG_MASK_DT(DT_NODELABEL(gpiote130), owned_channels) |                           \
	 NRFX_CONFIG_MASK_DT(DT_NODELABEL(gpiote130), child_owned_channels))

/** @brief Bitmask that defines GPIOTE131 channels reserved for use outside
 *         of the nrfx library.
 */
#define NRFX_GPIOTE131_CHANNELS_USED                                                               \
	(~NRFX_CONFIG_MASK_DT(DT_NODELABEL(gpiote131), owned_channels) |                           \
	 NRFX_CONFIG_MASK_DT(DT_NODELABEL(gpiote131), child_owned_channels))

/** @brief Bitmask that defines EGU instances that are reserved for use outside
 *         of the nrfx library.
 */
#define NRFX_EGUS_USED 0

/** @brief Bitmask that defines TIMER instances that are reserved for use outside
 *         of the nrfx library.
 */
#define NRFX_TIMERS_USED 0

/* If the GRTC system timer driver is to be used, prepare definitions required
 * by the nrfx_grtc driver (NRFX_GRTC_CONFIG_ALLOWED_CC_CHANNELS_MASK and
 * NRFX_GRTC_CONFIG_NUM_OF_CC_CHANNELS) based on information from devicetree.
 */
#if DT_HAS_COMPAT_STATUS_OKAY(nordic_nrf_grtc)
#define NRFX_GRTC_CONFIG_ALLOWED_CC_CHANNELS_MASK \
	(NRFX_CONFIG_MASK_DT(DT_INST(0, nordic_nrf_grtc), owned_channels) & \
	 ~NRFX_CONFIG_MASK_DT(DT_INST(0, nordic_nrf_grtc), child_owned_channels))
#define NRFX_GRTC_CONFIG_NUM_OF_CC_CHANNELS \
	(DT_PROP_LEN_OR(DT_INST(0, nordic_nrf_grtc), owned_channels, 0) - \
	 DT_PROP_LEN_OR(DT_INST(0, nordic_nrf_grtc), child_owned_channels, 0))
#endif /* DT_HAS_COMPAT_STATUS_OKAY(nordic_nrf_grtc) */

/*
 * The enabled Bluetooth controller subsystem is responsible for providing
 * definitions of the BT_CTLR_USED_* symbols used below in a file named
 * bt_ctlr_used_resources.h and for adding its location to global include
 * paths so that the file can be included here for all Zephyr libraries that
 * are to be built.
 */
#if defined(CONFIG_BT_LL_SW_SPLIT)
#include <bt_ctlr_used_resources.h>
#if defined(CONFIG_SOC_SERIES_NRF51X) || defined(CONFIG_SOC_COMPATIBLE_NRF52X)
#define NRFX_PPI_CHANNELS_USED_BY_BT_CTLR BT_CTLR_USED_PPI_CHANNELS
#define NRFX_PPI_GROUPS_USED_BY_BT_CTLR   BT_CTLR_USED_PPI_GROUPS
#elif defined(CONFIG_SOC_COMPATIBLE_NRF53X)
#define NRFX_DPPI0_CHANNELS_USED_BY_BT_CTLR BT_CTLR_USED_PPI_CHANNELS
#define NRFX_DPPI0_GROUPS_USED_BY_BT_CTLR   BT_CTLR_USED_PPI_GROUPS
#elif defined(CONFIG_SOC_COMPATIBLE_NRF54LX)
#define NRFX_DPPI10_CHANNELS_USED_BY_BT_CTLR BT_CTLR_USED_PPI_CHANNELS
#define NRFX_DPPI10_GROUPS_USED_BY_BT_CTLR   BT_CTLR_USED_PPI_GROUPS
#endif
#endif /* defined(CONFIG_BT_LL_SW_SPLIT) */

#if defined(CONFIG_NRF_802154_RADIO_DRIVER)
#if defined(CONFIG_SOC_COMPATIBLE_NRF52X)
#include <../src/nrf_802154_peripherals_nrf52.h>
#define NRFX_PPI_CHANNELS_USED_BY_802154_DRV NRF_802154_PPI_CHANNELS_USED_MASK
#define NRFX_PPI_GROUPS_USED_BY_802154_DRV   NRF_802154_PPI_GROUPS_USED_MASK
#elif defined(CONFIG_SOC_COMPATIBLE_NRF53X)
#include <../src/nrf_802154_peripherals_nrf53.h>
#define NRFX_DPPI0_CHANNELS_USED_BY_802154_DRV NRF_802154_DPPI_CHANNELS_USED_MASK
#define NRFX_DPPI0_GROUPS_USED_BY_802154_DRV   NRF_802154_DPPI_GROUPS_USED_MASK
#elif defined(CONFIG_SOC_COMPATIBLE_NRF54LX)
#include <../src/nrf_802154_peripherals_nrf54l.h>
#define NRFX_DPPI10_CHANNELS_USED_BY_802154_DRV NRF_802154_DPPI_CHANNELS_USED_MASK
#define NRFX_DPPI10_GROUPS_USED_BY_802154_DRV   NRF_802154_DPPI_GROUPS_USED_MASK
#elif defined(CONFIG_SOC_SERIES_NRF54HX)
#include <../src/nrf_802154_peripherals_nrf54h.h>
#define NRFX_DPPI020_CHANNELS_USED_BY_802154_DRV NRF_802154_DPPI_CHANNELS_USED_MASK
#define NRFX_DPPI020_GROUPS_USED_BY_802154_DRV   NRF_802154_DPPI_GROUPS_USED_MASK
#else
#error Unsupported chip family
#endif
#endif /* CONFIG_NRF_802154_RADIO_DRIVER */

#define VALUE_OR_ZERO(x) \
	COND_CODE_0(IS_EMPTY(x), x, (0))

#define COMMON_MASKS(peripheral, type) \
	(VALUE_OR_ZERO(NRFX_##peripheral##_##type##_USED_BY_BT_CTLR) | \
	 VALUE_OR_ZERO(NRFX_##peripheral##_##type##_USED_BY_802154_DRV) | \
	 VALUE_OR_ZERO(NRFX_##peripheral##_##type##_USED_BY_MPSL))

#define PPI_CHANNELS_MASKS()              COMMON_MASKS(PPI, CHANNELS)
#define PPI_GROUPS_MASKS()                COMMON_MASKS(PPI, GROUPS)
#define DPPI_CHANNELS_MASKS(inst)         COMMON_MASKS(DPPI##inst, CHANNELS)
#define DPPI_GROUPS_MASKS(inst)           COMMON_MASKS(DPPI#inst, GROUPS)
#define PPIB_CHANNELS_MASKS(insta, instb) COMMON_MASKS(PPIB_##insta##_##instb, CHANNELS)

#define NRFX_PPI_CHANNELS_USED PPI_CHANNELS_MASKS()
#define NRFX_PPI_GROUPS_USED   PPI_GROUPS_MASKS()

#define NRFX_DPPI0_CHANNELS_USED DPPI_CHANNELS_MASKS(0)
#define NRFX_DPPI0_GROUPS_USED   DPPI_GROUPS_MASKS(0)

#define NRFX_DPPI00_CHANNELS_USED DPPI_CHANNELS_MASKS(00)
#define NRFX_DPPI00_GROUPS_USED   DPPI_GROUPS_MASKS(00)

#define NRFX_DPPI10_CHANNELS_USED DPPI_CHANNELS_MASKS(10)
#define NRFX_DPPI10_GROUPS_USED   DPPI_GROUPS_MASKS(10)

#define NRFX_DPPI20_CHANNELS_USED DPPI_CHANNELS_MASKS(20)
#define NRFX_DPPI20_GROUPS_USED   DPPI_GROUPS_MASKS(20)

#define NRFX_DPPI30_CHANNELS_USED DPPI_CHANNELS_MASKS(30)
#define NRFX_DPPI30_GROUPS_USED   DPPI_GROUPS_MASKS(30)

#define NRFX_DPPI020_CHANNELS_USED DPPI_CHANNELS_MASKS(020)
#define NRFX_DPPI020_GROUPS_USED   DPPI_GROUPS_MASKS(020)

#define NRFX_DPPI030_CHANNELS_USED DPPI_CHANNELS_MASKS(030)
#define NRFX_DPPI030_GROUPS_USED   DPPI_GROUPS_MASKS(030)

#define NRFX_DPPI120_CHANNELS_USED DPPI_CHANNELS_MASKS(120)
#define NRFX_DPPI120_GROUPS_USED   DPPI_GROUPS_MASKS(120)

#define NRFX_DPPI130_CHANNELS_USED DPPI_CHANNELS_MASKS(130)
#define NRFX_DPPI130_GROUPS_USED   DPPI_GROUPS_MASKS(130)

#define NRFX_DPPI131_CHANNELS_USED DPPI_CHANNELS_MASKS(131)
#define NRFX_DPPI131_GROUPS_USED   DPPI_GROUPS_MASKS(131)

#define NRFX_DPPI132_CHANNELS_USED DPPI_CHANNELS_MASKS(132)
#define NRFX_DPPI132_GROUPS_USED   DPPI_GROUPS_MASKS(132)

#define NRFX_DPPI133_CHANNELS_USED DPPI_CHANNELS_MASKS(133)
#define NRFX_DPPI133_GROUPS_USED   DPPI_GROUPS_MASKS(133)

#define NRFX_DPPI134_CHANNELS_USED DPPI_CHANNELS_MASKS(134)
#define NRFX_DPPI134_GROUPS_USED   DPPI_GROUPS_MASKS(134)

#define NRFX_DPPI135_CHANNELS_USED DPPI_CHANNELS_MASKS(135)
#define NRFX_DPPI135_GROUPS_USED   DPPI_GROUPS_MASKS(135)

#define NRFX_DPPI136_CHANNELS_USED DPPI_CHANNELS_MASKS(136)
#define NRFX_DPPI136_GROUPS_USED   DPPI_GROUPS_MASKS(136)

#define NRFX_DPPI_CHANNELS_USED NRFX_DPPI0_CHANNELS_USED
#define NRFX_DPPI_GROUPS_USED   NRFX_DPPI0_GROUPS_USED

#define NRFX_PPIB_INTERCONNECT_00_10_CHANNELS_USED  PPIB_CHANNELS_MASKS(00, 10)
#define NRFX_PPIB_INTERCONNECT_01_20_CHANNELS_USED  PPIB_CHANNELS_MASKS(01, 20)
#define NRFX_PPIB_INTERCONNECT_11_21_CHANNELS_USED  PPIB_CHANNELS_MASKS(11, 21)
#define NRFX_PPIB_INTERCONNECT_22_30_CHANNELS_USED  PPIB_CHANNELS_MASKS(22, 30)
#define NRFX_PPIB_INTERCONNECT_02_03_CHANNELS_USED  PPIB_CHANNELS_MASKS(02, 03)
#define NRFX_PPIB_INTERCONNECT_04_12_CHANNELS_USED  PPIB_CHANNELS_MASKS(04, 12)
#define NRFX_PPIB_INTERCONNECT_020_030_CHANNELS_USED PPIB_CHANNELS_MASKS(020, 030)

#endif /* NRFX_RESERVED_RESOURCES_H__ */
